server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: fastapi-logs
    static_configs:
      - targets:
          - service1:8000
          - service2:8001
        labels:
          job: fastapi
          __path__: /var/log/*.log